default:
		avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o main.o main.c
		avr-gcc -o main.bin main.o
		avr-objcopy -O ihex -R .eeprom main.bin main.hex
		sudo avrdude -F -V -c arduino -p ATMEGA328P -P /dev/cu.usbmodem1401 -b 115200 -U flash:w:main.hex